name: Deploy static site to Azure Web App - UCCD2323-GroupAlimama

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'UCCD2323-GroupAlimama'
          package: '.'

          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6B9EAFFC44EF4B7CB6B3E0EEC88A2173 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'groupalimama'
          slot-name: 'Production'
          package: .
          
